name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          cd website
          git config --global user.email "kevingpqi@gmail.com"
          git config --global user.name "kevingpqi123"
          yarn install --frozen-lockfile
          yarn build

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: website/build/libpag.github.io
          destination-github-username: 'libpag'
          destination-repository-name: 'libpag.github.io'
          user-email: kevingpqi@gmail.com
          commit-message: Deploy website
          target-branch: master


