name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          cd website
          npm install
          npm run-script build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_DEPLOY }}
          BRANCH: gh-pages
          FOLDER: website/build
          BUILD_SCRIPT: cd website && npm install && npm run build
