name: Deploy to GitHub Pages

on:
  push:
    branches: [feature/test]

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          cd website 
          git config --global user.email "kevingpqi@gmail.com"
          git config --global user.name "kevingpqi123"
          
          echo "*********start***********"
          yarn install --frozen-lockfile
          yarn deploy
